services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3.7.8
    container_name: lavalink
    environment:
      # set Java options here
      - _JAVA_OPTIONS=-Xmx6G
      # set lavalink server port
      - SERVER_PORT=2333
      # set password for lavalink
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./lavalink.yaml:/opt/Lavalink/application.yml:ro
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis

  wisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    environment:
      ASR_ENGINE: faster_whisper
      ASR_MODEL: medium

  booty:
    image: registry.heavycookie.co/thibault.lacroux/booty:latest
    container_name: booty
    environment:
      REDIS_URL: redis://redis/
      LAVALINK_HOST: lavalink
      LAVALINK_PASSWORD: youshallnotpass
    volumes:
      - ./db.sqlite:/usr/src/app/db.sqlite
