services:
  lavalink:
    extends:
      file: docker-compose.base.yml
      service: lavalink
    ports:
      - 2333:2333
    volumes:
      - ./lavalink.yaml:/opt/Lavalink/application.yml:ro

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    ports:
      - 6379:6379

  whisper:
    extends:
      file: docker-compose.base.yml
      service: whisper
    ports:
      - 9000:9000
