services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3.7.8
    container_name: lavalink
    environment:
      # set Java options here
      _JAVA_OPTIONS: -Xmx6G
      # set lavalink server port
      SERVER_PORT: 2333
      # set password for lavalink
      LAVALINK_SERVER_PASSWORD: youshallnotpass

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper
    environment:
      ASR_ENGINE: faster_whisper
      ASR_MODEL: medium
